packaging_format = 2

id = "bonfire"
name = "Bonfire"

version = "1.0.0-rc.2.3~ynh1"

maintainers = ["Lapineige"]

[description]
en = "Federated social networking server built on ActivityPub open protocol"
fr = "Serveur de réseautage social fédéré basé sur le protocole ouvert ActivityPub"

[upstream]
license = "AGPL-3.0-only"
website = "https://bonfirenetworks.org/"
demo = "https://playground.bonfire.cafe/"
admindoc = "https://bonfirenetworks.org/docs/"
userdoc = "https://bonfirenetworks.org/docs/"
code = "https://github.com/bonfire-networks/bonfire-app"

[integration]
yunohost = ">= 11.1.18"
multi_instance = false
architectures = "all"
ldap = false
sso = false
disk = "3000M"
ram.build = "2000M"
ram.runtime = "1000M"

[install]
  [install.domain]
  type = "domain"
  help.en = "The domain name to use. Bonfire will be installed at its root path (/). This can't be changed."
  help.fr = "Nom de domaine à utiliser. Bonfire sera installé à sa racine (/). Cela ne pourra pas être changé."

  [install.is_public]
    type = "boolean"
    default = true
    help.en = "Should that instance be visible to the fediverse ? It is required for federation."
    help.fr = "Cette instance doit elle être visible sur le fédiverse? C'est nécessaire pour la fédération."

  [install.init_main_permission]
    type = "group"
    default = "visitors"

  [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"
    
  [install.admin]
    type = "user"

  [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"
    
  [install.media_upload_size]
    ask.en = "Choose the maximum size of the media uploaded. Can be changed later."
    ask.fr = "Choisissez la taille maximale des médias mis en ligne. Peut-être modifié ultérieurement."
    type = "select"
    choices = [
      "1MB",
      "2MB",
      "5MB",
      "10MB",
      "15MB",
      "20MB",
      "35MB",
      "50MB",
      "70MB",
      "100MB",
      "150MB"
      ]
    default = "35MB"

[resources]

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/bonfire-networks/bonfire-app/archive/refs/tags/v1.0.0-rc.2.3.tar.gz"
    sha256 = "0eff40c325ede923491c3d435269f1f753630fba70bbf4a07b2fc74057c262ec"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"

    [resources.apt]
    packages = "postgresql postgresql-contrib postgresql-15-postgis-3 curl ca-certificates git imagemagick libvips-tools poppler-utils ffmpeg build-essential autoconf m4 libncurses5-dev libssh-dev unixodbc-dev libgmp3-dev libsctp-dev erlang-dev erlang-parsetools erlang-os-mon erlang-tools erlang-xmerl npm node-postcss"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = ["yarn"]

    extras.just.repo = "deb https://proget.makedeb.org prebuilt-mpr bookworm"
    extras.just.key = "https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub"
    extras.just.packages = ["just"]

    [resources.database]
    type = "postgresql"
