packaging_format = 2

id = "bonfire"
name = "Bonfire"

version = "0.9.8-beta.26~ynh3"

maintainers = ["Lapineige"]

[description]
en = "Federated social networking server built on ActivityPub open protocol"
fr = "Serveur de réseautage social fédéré basé sur le protocole ouvert ActivityPub"

[upstream]
license = "AGPL-3.0-only"
website = "https://bonfirenetworks.org/"
demo = "https://playground.bonfire.cafe/"
admindoc = "https://bonfirenetworks.org/docs/"
userdoc = "https://bonfirenetworks.org/docs/"
code = "https://github.com/bonfire-networks/bonfire-app"

[integration]
yunohost = ">= 11.1.18"
multi_instance = false
architectures = "all"
ldap = false
sso = false
disk = "3000M"
ram.build = "500M"
ram.runtime = "1000M"

[install]
  [install.domain]
  type = "domain"
  help.en = "The domain name to use. Bonfire will be installed at its root path (/). This can't be changed."
  help.fr = "Nom de domaine à utiliser. Bonfire sera installé à sa racine (/). Cela ne pourra pas être changé."

  [install.is_public]
    type = "boolean"
    default = true
    help.en = "Should that instance be visible to the fediverse ? It is required for federation."
    help.fr = "Cette instance doit elle être visible sur le fédiverse? C'est nécessaire pour la fédération."

  [install.init_main_permission]
    type = "group"
    default = "visitors"

  [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"
    
  [install.admin]
    type = "user"

  [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"
    
  [install.media_upload_size]
    ask.en = "Choose the maximum size of the media uploaded. Can be changed later."
    ask.fr = "Choisissez la taille maximale des médias mis en ligne. Peut-être modifié ultérieurement."
    type = "select"
    choices = [
      "1MB",
      "2MB",
      "5MB",
      "10MB",
      "15MB",
      "20MB",
      "35MB",
      "50MB",
      "70MB",
      "100MB",
      "150MB"
      ]
    default = "35MB"

[resources]

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "docker.io docker-compose"

    [resources.database]
    type = "postgresql"
