#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression "Stoping Bonfire..."

"$release_folder/bin/bonfire stop"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
